typeof ''                   // "string"
typeof 1                    // "number"
typeof NaN                  // "number"
typeof true                 // "boolean"
typeof undefined            // "undefined"
typeof Symbol()             // "Symbol"
typeof null                 // "object"
typeof []                   // "object"
typeof {}                   // "object"
typeof new Date()           // "object"
typeof /test/gi             // "object"
typeof fucntion () {}       // "function"
